replicaCount: 1

image:
  repository: 2tunnels/starlettelab
  pullPolicy: Always
  tag: CHANGE-ME

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: starlettelab.2tunnels.com

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
