name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install bump2version
        run: python -m pip install bump2version
      - name: Configure git
        run: |
          git config --local user.name "The Octocat"
          git config --local user.email "octocat@github.com"
      - name: Bump version
        run: bump2version patch
      - name: Create new release
        run: git push --follow-tags
