name: release

on:
  push:
    branches: [ master ]

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'Bump version')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: python -m pip install -U pip setuptools poetry
      - name: Configure git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
      - name: Bump version
        run: poetry version patch
      - name: Release new version
        run: |
          VERSION=$(poetry version | cut -d " " -f 2)
          git add pyproject.toml
          git commit -m "Bump version ${VERSION}"
          git tag "v${VERSION}"
          git push origin --tags
